name: test ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install Node modules
      run: npm i

    - name: Unit & Integration tests
      run: npm run ci:test

    - name: Lint
      run: npm run ci:lint

    - name: Type check
      run: npm run ci:types-check
